title = "gitleaks config"

[[regexes]]
description = "Password"
regex = '''(?i)[\w]*password[\w]*[:=>, ]+['"][\S]{3,}['"]'''
[[regexes]]
description = "Sinatra session secret"
regex = '''(?i)session_secret[:=>, ]+['"][0-9a-zA-Z]{3,}['"]'''
[[regexes]]
description = "Webhook secret"
regex = '''(?i)webhook_secret[:=>, ]+['"][\S]{3,}['"]'''
[[regexes]]
description = "AWS"
regex = '''AKIA[0-9A-Z]{16}'''
[[regexes]]
description = "RKCS8"
regex = '''-----BEGIN PRIVATE KEY-----'''
[[regexes]]
description = "RSA"
regex = '''-----BEGIN RSA PRIVATE KEY-----'''
[[regexes]]
description = "Github"
regex = '''(?i)github.*['\"][0-9a-zA-Z]{35,40}['\"]'''
[[regexes]]
description = "SSH"
regex = '''-----BEGIN OPENSSH PRIVATE KEY-----'''
[[regexes]]
description = "Facebook"
regex = '''(?i)facebook.*['\"][0-9a-f]{32}['\"]'''
[[regexes]]
description = "Twitter"
regex = '''(?i)twitter.*['\"][0-9a-zA-Z]{35,44}['\"]'''
[[regexes]]
description = "PGP"
regex = '''-----BEGIN PGP PRIVATE KEY BLOCK-----'''
[[regexes]]
description = "Slack token"
regex = '''xox[baprs]-.*'''
[[regexes]]
description = "Strip API Key"
regex = '''(?i)(sk|pk)_(test|live)_[0-9a-zA-Z]{10,32}'''

[whitelist]
commits = []
files = [
  '\.gitleaks\.toml',
  '(.*?)(jpg|gif|doc|pdf|bin|md)$',
]
regexes = [
  # Values set by environment variables
  '''ENV\[[\S]+\]''',
  '''ENV\.fetch\([\S]+\)''',
]
