version: 2.1

orbs:
  docker-publish: circleci/docker-publish@0.1.6

workflows:
  build_and_publish:
    jobs:
      - docker-publish/publish:
          context: quay.io
          registry: quay.io
          image: upennlibraries/alma-webhook
          tag: circleci.${CIRCLE_BUILD_NUM}
