version: 2.1

orbs:
  docker-publish: upenn-libraries/docker-publish@0.1.0
  gitleaks: upenn-libraries/gitleaks@0.1.0

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.1
      - image: quay.io/upennlibraries/alma-webhook:${CIRCLE_SHA1}
    steps:
      - run:
          name: Smoke Test Container
          command: |
            wget \
              -q -t 5 --retry-connrefused -O /dev/null \
              http://localhost:80/

workflows:
  build_and_publish:
    jobs:
      - gitleaks/check_local:
          image: quay.io/upennlibraries/gitleaks:v1.24.0
          options: --redact --repo-config
      - docker-publish/publish:
          context: quay.io
          registry: quay.io
          image: upennlibraries/alma-webhook
          label_prefix: edu.upenn.library
      - test:
          requires:
            - docker-publish/publish
